# Generated by Django 5.1.7 on 2025-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_sentimentcategory_sentimentcategoryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
