# Generated by Django 5.1.7 on 2025-03-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_cohort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.category'),
        ),
        migrations.DeleteModel(
            name='QuestionCategoryAssignment',
        ),
    ]
