# Generated by Django 5.1.7 on 2025-03-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_category_delete_questioncategoryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.cohort'),
        ),
        migrations.DeleteModel(
            name='CohortMember',
        ),
    ]
