# Generated by Django 5.1.7 on 2025-03-24 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_participant_cohort_delete_cohortmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='cohort',
        ),
        migrations.AddField(
            model_name='cohort',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.participant'),
        ),
    ]
