# Generated by Django 5.1.7 on 2025-03-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_cohort_participant_cohort_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='participants',
        ),
        migrations.AddField(
            model_name='participant',
            name='cohorts',
            field=models.ManyToManyField(to='survey.cohort'),
        ),
    ]
