# Generated by Django 5.1.7 on 2025-03-24 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_cohort_participants_participant_cohorts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentcategoryassignment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sentimentcategoryassignment',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='answer',
            name='sentiments',
            field=models.ManyToManyField(to='survey.sentiment'),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.sentimentcategory'),
        ),
        migrations.DeleteModel(
            name='SentimentAssignment',
        ),
        migrations.DeleteModel(
            name='SentimentCategoryAssignment',
        ),
    ]
