# Generated by Django 5.1.7 on 2025-03-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_remove_sentimentcategoryassignment_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='QuestionCategory',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(to='survey.questioncategory'),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='categories',
            field=models.ManyToManyField(to='survey.sentimentcategory'),
        ),
    ]
