# Generated by Django 5.1.7 on 2025-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_rename_category_questioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('NUMERIC', 'Numeric Rating'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='UNSPECIFIED', max_length=50),
        ),
    ]
