# Generated by Django 5.1.7 on 2025-03-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_alter_question_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
